
package com.aes.service.accounts.model;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OrderManagementIFExport1_OrderManagementIFHttpService", targetNamespace = "http://OrderManagementLib/com/touresbalon/interfaces/OrderManagementIF", wsdlLocation = "file:/E:/especializacion/Segundo%20Semestre/oms/src/main/resources/wsdl/OrderManagementIFExport.wsdl")
public class OrderManagementIFExport1OrderManagementIFHttpService
    extends Service
{

    private final static URL ORDERMANAGEMENTIFEXPORT1ORDERMANAGEMENTIFHTTPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.aes.service.accounts.model.OrderManagementIFExport1OrderManagementIFHttpService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.aes.service.accounts.model.OrderManagementIFExport1OrderManagementIFHttpService.class.getResource(".");
            url = new URL(baseUrl, "file:/E:/especializacion/Segundo%20Semestre/oms/src/main/resources/wsdl/OrderManagementIFExport.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/E:/especializacion/Segundo%20Semestre/oms/src/main/resources/wsdl/OrderManagementIFExport.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ORDERMANAGEMENTIFEXPORT1ORDERMANAGEMENTIFHTTPSERVICE_WSDL_LOCATION = url;
    }

    public OrderManagementIFExport1OrderManagementIFHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderManagementIFExport1OrderManagementIFHttpService() {
        super(ORDERMANAGEMENTIFEXPORT1ORDERMANAGEMENTIFHTTPSERVICE_WSDL_LOCATION, new QName("http://OrderManagementLib/com/touresbalon/interfaces/OrderManagementIF", "OrderManagementIFExport1_OrderManagementIFHttpService"));
    }

    /**
     * 
     * @return
     *     returns OrderManagementIF
     */
    @WebEndpoint(name = "OrderManagementIFExport1_OrderManagementIFHttpPort")
    public OrderManagementIF getOrderManagementIFExport1OrderManagementIFHttpPort() {
        return super.getPort(new QName("http://OrderManagementLib/com/touresbalon/interfaces/OrderManagementIF", "OrderManagementIFExport1_OrderManagementIFHttpPort"), OrderManagementIF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderManagementIF
     */
    @WebEndpoint(name = "OrderManagementIFExport1_OrderManagementIFHttpPort")
    public OrderManagementIF getOrderManagementIFExport1OrderManagementIFHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://OrderManagementLib/com/touresbalon/interfaces/OrderManagementIF", "OrderManagementIFExport1_OrderManagementIFHttpPort"), OrderManagementIF.class, features);
    }

}
